Leaderboard: setup project
akos29/Leader-Board pull request #1
Opened 2022-11-22 12:20 UTC by akos29

### Leaderboard: setup project

This request includes: 

- setup leaderboard project using webpack 
- Add index webpage with style

2022-11-22 21:38 UTC, mckent05 requested changes
Hi @akos29,

# STATUS: CHANGES REQUIRED ♻️ ♻️  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/203426257-0afb71ee-2791-458a-b5b2-7ee218cee3e2.gif)

## Highlights
- All linter checks are passing ✔️ ✔️ 
- PR looks professional 👏 👏 
- Gitflow was rightly followed 👍 👍 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-22 21:38 UTC, mckent05 commented on src/index.js
> +component();
- I suggest that this function listens to an event listener. You can consider using `DOMContentLoaded`. This ensures that you follow javascript best practices, please fix this 👍 👍

2022-11-23 05:43 UTC, jerryowusu approved these changes
Hi @akos29 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200w](https://user-images.githubusercontent.com/65233860/203478091-d78eb544-6fe0-4411-aa8b-72adf75c9e07.gif)


## Highlights
All linters are passing :heavy_check_mark: 
Good commit messages :heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-23 05:43 UTC, jerryowusu commented on README.md
> +[Live Demo Link](https://akos29.github.io/To-do-list/)
[OPTIONAL] Kindly update the live demo link to show the correct project since the available link points to a different project. :wink:

2022-11-23 06:01 UTC, merged